#!/usr/bin/env python3
"""
Redact proprietary sample-level data from the deposited supplementary tables and logs.

This is the script referenced by §B and §C1/C2 of the release plan. It is kept in the
repository so that the redaction is auditable: anyone can re-run it and confirm that the
published tables are exactly what this code produces.

Two rules are implemented:

R2  No expression and no annotation from a proprietary cohort may be published, including
    sample names. Redaction is row-wise: every column survives, the 1,996 proprietary rows
    do not. `comb_ann_public.csv` is the exception that proves the rule — it arrives
    already row-filtered, yet 76 of its surviving rows still named a proprietary sample in
    a *column*, so that table is redacted column-wise as well.
R3  An internal, unpublished label is removed from `Major_group` and `Diagnosis_with_coo`.
    It is a *label rename only*; no sample changes group, so no published count moves.
    The label itself is not written here — the public tables no longer contain it, and
    naming it would defeat the removal. Pass --legacy-label to re-apply the rename when
    auditing against an unredacted checkout.

Cohort *names* are deliberately left intact everywhere (rule R1) — `Supplementary File 1
short.csv` keeps all 88 cohorts, proprietary ones included, because naming a cohort that
cannot be redistributed is what tells a reader where to apply for it.

Run from the repository root:

    python make_public_supplementary.py [--check]

`--check` reports what would change without writing anything.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent
SUPP = ROOT / "figures_for_article"

# Source of truth for which cohorts may not be redistributed. These live *inside* the tree
# this script redacts, so after a successful run the full table no longer contains the
# proprietary rows it was derived from and the script becomes a no-op. Point --source-root
# at an unredacted copy of the repository to re-derive and re-audit.
SOT_DIR = Path("figures_for_article") / "supplementary_260824"
SHORT_NAME = "Supplementary File 1 short.csv"
FULL_NAME = "Supplementary File 1.csv"

COMB_ANN_NAME = "comb_ann_public.csv"

EXPECTED_COHORTS = 15
EXPECTED_PROP_IDS = 1996
EXPECTED_PUBLIC_ROWS = 5178  # 7,174 annotated samples − 1,996 proprietary

LEGACY_LABEL_REPLACEMENT = "Normal_B_cells"

REDACTED_TOKEN = "<redacted-sample>"

WITHHELD_NOTE = """\
# Withheld samples

The analysis behind this article used **7,174 samples from 88 cohorts**. The tables in this
directory list **{public} samples from {open_n} cohorts**: the {prop_n} cohorts below are
proprietary or under controlled access and neither their expression values nor their
per-sample annotation — including their sample identifiers — may be redistributed here.

The withheld cohorts are still *named* in `Supplementary File 1 short.csv`, together with
the sample count each contributed, so that every number quoted in the article remains
traceable and so that readers know where to apply for the underlying data.

**This is a redaction of the deposited table, not a discrepancy in the science.** Every
statistic, figure and metric in the article was computed on the full 7,174 samples.

| Cohort | Samples withheld | Where to apply |
|---|---:|---|
{rows}

For `PUB_DLBCL_NCICCR`, apply through dbGaP study **phs001444.v2.p1**. For the remaining
cohorts, contact the originating group; `Supplementary File 1 short.csv` records what is
known about each one's provenance.

*Generated by `make_public_supplementary.py`. Do not edit by hand.*
"""

APPLY_TO_APPLY = {
    "PUB_DLBCL_NCICCR": "dbGaP phs001444.v2.p1 (controlled access)",
}


class AlreadyRedacted(RuntimeError):
    """Raised when the source-of-truth tables carry no proprietary rows to derive from."""


def load_cohort_tables(
    source_root: Path,
) -> tuple[set[str], set[str], set[str], set[str], dict[str, int]]:
    """
    Reads the two source-of-truth tables and derives the proprietary sample-ID set.

    The ID list is derived rather than typed because the proprietary cohorts use twelve
    different identifier shapes (``MPI-###``, ``CTSP-…``, ``FL###-…``, ``pt_#_#``, …); any
    hand-written regex over those shapes would miss some.

    Returns
    -------
    prop_cohorts
        The 15 cohort labels marked ``Proprietary``.
    open_cohorts
        The remaining 73 cohort labels.
    prop_ids
        The 1,996 sample identifiers belonging to a proprietary cohort.
    open_ids
        The 5,178 identifiers belonging to a non-proprietary cohort.
    prop_counts
        Sample count per proprietary cohort, for the withheld-samples note.
    """
    short_table = source_root / SOT_DIR / SHORT_NAME
    full_table = source_root / SOT_DIR / FULL_NAME
    short_rows = list(csv.DictReader(short_table.open(encoding="utf-8")))
    prop_cohorts = {
        r["COHORT_LABEL"].strip()
        for r in short_rows
        if r["Cohort type"].strip() == "Proprietary"
    }
    open_cohorts = {r["COHORT_LABEL"].strip() for r in short_rows} - prop_cohorts
    prop_counts = {
        r["COHORT_LABEL"].strip(): int(r["sample count"])
        for r in short_rows
        if r["COHORT_LABEL"].strip() in prop_cohorts
    }

    full_rows = list(csv.DictReader(full_table.open(encoding="utf-8")))
    id_col = list(full_rows[0])[0]
    prop_ids = {r[id_col] for r in full_rows if r["COHORT_LABEL"] in prop_cohorts}
    open_ids = {r[id_col] for r in full_rows} - prop_ids

    if not prop_ids and len(open_ids) == EXPECTED_PUBLIC_ROWS:
        raise AlreadyRedacted(
            f"{full_table} already holds {len(open_ids)} rows and no proprietary sample, "
            "so this tree has been redacted. Pass --source-root <unredacted-checkout> to "
            "re-derive the withheld set and re-audit."
        )

    assert len(prop_cohorts) == EXPECTED_COHORTS, len(prop_cohorts)
    assert len(prop_ids) == EXPECTED_PROP_IDS, len(prop_ids)
    assert len(open_ids) == EXPECTED_PUBLIC_ROWS, len(open_ids)
    return prop_cohorts, open_cohorts, prop_ids, open_ids, prop_counts


def make_is_public(
    prop_cohorts: set[str],
    open_cohorts: set[str],
    prop_ids: set[str],
    open_ids: set[str],
):
    """
    Builds a deny-by-default classifier for a single sample identifier.

    `Supplementary File 2` covers 7,238 samples — 64 more than `Supplementary File 1`,
    because those samples carry annotation but no expression and so never entered the
    analysis table. Neither test alone is sufficient for them:

    * Membership in ``prop_ids`` misses 40 of the extras that belong to proprietary
      cohorts — 17 suffix-matching ``COLL_DLBCL_UMLOSSOSTRANSL`` and 23 bearing the
      ``MPI-###`` shape of the SOM cohort — so a naive filter would publish their names.
    * Suffix attribution alone wrongly withholds 710 open samples whose identifier is a
      bare accession (``GSM1684982``) carrying no ``-<COHORT_LABEL>`` suffix.

    So the two source-of-truth sets are consulted first, and suffix attribution is used
    only for identifiers absent from `Supplementary File 1`. Anything that still cannot be
    positively attributed to an open cohort is withheld.
    """

    def is_public(sample_id: str) -> bool:
        if sample_id in prop_ids:
            return False
        if sample_id in open_ids:
            return True
        for cohort in prop_cohorts:
            if sample_id.endswith("-" + cohort) or sample_id.startswith(cohort + "-"):
                return False
        for cohort in open_cohorts:
            if sample_id.endswith("-" + cohort):
                return True
        return False

    return is_public


def scrub_legacy_label(row: dict[str, str], legacy_label: str | None) -> int:
    """
    Renames the internal group label in one annotation row; returns the number of edits.

    `legacy_label` is supplied on the command line rather than hard-coded, so that the
    published copy of this script does not itself carry the name it exists to remove.
    With no label given the rename is a no-op, which is the correct behaviour against an
    already-redacted tree.
    """
    if not legacy_label:
        return 0
    edits = 0
    if row.get("Major_group") == legacy_label:
        row["Major_group"] = LEGACY_LABEL_REPLACEMENT
        edits += 1
    coo = row.get("Diagnosis_with_coo", "")
    if coo.startswith(legacy_label + "_"):
        row["Diagnosis_with_coo"] = (
            LEGACY_LABEL_REPLACEMENT + coo[len(legacy_label) + 1:]
        )
        edits += 1
    return edits


def redact_supp_file_1(
    path: Path, prop_cohorts: set[str], legacy_label: str | None, check: bool
) -> str:
    rows = list(csv.DictReader(path.open(encoding="utf-8")))
    fields = list(rows[0])
    kept = [r for r in rows if r["COHORT_LABEL"] not in prop_cohorts]
    renames = sum(scrub_legacy_label(r, legacy_label) for r in kept)
    if not check:
        with path.open("w", newline="", encoding="utf-8") as fh:
            w = csv.DictWriter(fh, fieldnames=fields)
            w.writeheader()
            w.writerows(kept)
    return f"{len(rows)} → {len(kept)} rows, {renames} legacy-label renames"


def parse_column_renames(spec: str | None) -> dict[str, str]:
    """
    Parses a ``old=new,old=new`` command-line spec into a rename mapping.

    Parameters
    ----------
    spec:
        Comma-separated ``old=new`` pairs, or None.

    Returns
    -------
    dict[str, str]
        Empty when no spec is given, which makes the rename a no-op.
    """
    if not spec:
        return {}
    pairs = {}
    for item in spec.split(","):
        old, _, new = item.partition("=")
        if not old.strip() or not new.strip():
            raise ValueError(f"bad --legacy-columns entry: {item!r}")
        pairs[old.strip()] = new.strip()
    return pairs


def redact_comb_ann_public(
    path: Path,
    prop_ids: set[str],
    legacy_label: str | None,
    column_renames: dict[str, str],
    check: bool,
) -> str:
    """
    Redacts the deposited annotation table in place.

    Five edits, all idempotent, so a second run against an already-redacted file
    reports zeros and writes an identical table:

    1. R2 — blanks `PUBLIC_SAMPLE_LABEL` wherever it holds a proprietary sample name.
       The table is already row-filtered to the open cohorts, but that filter keys on
       the index; open-cohort rows can still carry a proprietary label in this column.
    2. R3 — the same `Major_group` / `Diagnosis_with_coo` rename applied to
       Supplementary File 1, via `scrub_legacy_label`, then a sweep of *every*
       remaining column for the same label. The sweep is what makes this table safe:
       it carries the label in a third column, `Diagnosis_cell_type_general`, that
       Supplementary File 1 does not have, so naming columns explicitly misses 710
       cells here.
    3. Drops `AUTHOR`, which holds a colleague's work address in every populated row.
    4. Drops every column empty across all rows — internal-schema names with no
       content, two of which also carry the internal product name in the header.
    5. Renames the columns named in `column_renames`, supplied on the command line for
       the same reason as `legacy_label`.

    Parameters
    ----------
    path:
        The annotation CSV, rewritten in place unless `check`.
    prop_ids:
        The proprietary sample-ID set used for edit 1.
    legacy_label:
        Internal group label for edit 2; None makes it a no-op.
    column_renames:
        Header mapping for edit 5; empty makes it a no-op.
    check:
        Report only; write nothing.

    Returns
    -------
    str
        One-line summary of what changed.
    """
    rows = list(csv.DictReader(path.open(encoding="utf-8")))
    fields = list(rows[0])

    blanked = 0
    for row in rows:
        if row.get("PUBLIC_SAMPLE_LABEL") in prop_ids:
            row["PUBLIC_SAMPLE_LABEL"] = ""
            blanked += 1

    renames = sum(scrub_legacy_label(r, legacy_label) for r in rows)
    swept = 0
    if legacy_label:
        for row in rows:
            for col, value in row.items():
                if value == legacy_label:
                    row[col] = LEGACY_LABEL_REPLACEMENT
                    swept += 1
                elif value.startswith(legacy_label + "_"):
                    row[col] = (
                        LEGACY_LABEL_REPLACEMENT + value[len(legacy_label) + 1:]
                    )
                    swept += 1

    dropped_pii = [c for c in ("AUTHOR",) if c in fields]
    # A column counts as empty only if no row holds a non-blank value. Testing the
    # raw strings is what makes this correct here: every value arrives from csv as a
    # str, so "" is the only empty, and a pandas-style truthiness test on a coerced
    # column would keep all 486.
    dropped_empty = [
        c for c in fields
        if c not in dropped_pii and not any(r[c].strip() for r in rows)
    ]
    drop = set(dropped_pii) | set(dropped_empty)
    kept_fields = [c for c in fields if c not in drop]

    renamed = {o: n for o, n in column_renames.items() if o in kept_fields}
    out_fields = [renamed.get(c, c) for c in kept_fields]

    if not check:
        with path.open("w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(out_fields)
            for row in rows:
                w.writerow([row[c] for c in kept_fields])

    return (
        f"{len(rows)} rows kept; {len(fields)} → {len(kept_fields)} columns "
        f"({len(dropped_empty)} empty, {len(dropped_pii)} PII); "
        f"{blanked} sample labels blanked, {renames} legacy-label renames "
        f"(+{swept} swept from other columns), {len(renamed)} columns renamed"
    )


def redact_supp_file_2_csv(path: Path, is_public, check: bool) -> str:
    with path.open(encoding="utf-8") as fh:
        reader = csv.reader(fh)
        header = next(reader)
        rows = list(reader)
    kept = [r for r in rows if is_public(r[0])]
    if not check:
        with path.open("w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh)
            w.writerow(header)
            w.writerows(kept)
    return f"{len(rows)} → {len(kept)} rows"


def redact_supp_file_2_xlsx(path: Path, is_public, check: bool) -> str:
    """
    Rewrites the per-sample `Genes_per_sample` sheet, leaving the other three untouched.

    The sheet is replaced wholesale rather than row-deleted: `openpyxl.delete_rows` is
    O(n) per call and would take minutes across ~2,000 deletions. The replacement sheet is
    re-inserted at index 0 so the workbook's sheet order is unchanged.
    """
    wb = openpyxl.load_workbook(path)
    ws = wb["Genes_per_sample"]
    values = list(ws.values)
    header, body = values[0], values[1:]
    kept = [r for r in body if is_public(str(r[0]))]
    if not check:
        index = wb.sheetnames.index("Genes_per_sample")
        del wb["Genes_per_sample"]
        new = wb.create_sheet("Genes_per_sample", index)
        new.append(list(header))
        for row in kept:
            new.append(list(row))
        wb.save(path)
    return (
        f"Genes_per_sample {len(body)} → {len(kept)} rows; "
        f"other sheets preserved: {[s for s in wb.sheetnames if s != 'Genes_per_sample']}"
    )


def redact_log(path: Path, id_pattern: re.Pattern[str], check: bool) -> str:
    text = path.read_text(encoding="utf-8", errors="replace")
    redacted, n = id_pattern.subn(REDACTED_TOKEN, text)
    if not check and n:
        path.write_text(redacted, encoding="utf-8")
    return f"{n} proprietary sample identifiers redacted"


def write_withheld_note(directory: Path, prop_counts: dict[str, int],
                        public_rows: int, open_n: int, check: bool) -> str:
    """
    Writes the withheld-samples note as a sibling Markdown file.

    The plan called for a comment line prepended to the CSV. That is avoided deliberately:
    a leading `#` line is read as the header row by a plain `pd.read_csv`, which would
    corrupt a deposited table that reviewers open directly. A sibling note carries the same
    information and leaves the CSVs cleanly parseable.
    """
    rows = "\n".join(
        f"| {c} | {n} | {APPLY_TO_APPLY.get(c, 'contact the originating group')} |"
        for c, n in sorted(prop_counts.items(), key=lambda kv: -kv[1])
    )
    body = WITHHELD_NOTE.format(
        public=f"{public_rows:,}", open_n=open_n, prop_n=len(prop_counts), rows=rows
    )
    target = directory / "WITHHELD_SAMPLES.md"
    if not check:
        target.write_text(body, encoding="utf-8")
    return f"wrote {target.relative_to(ROOT)}"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="report what would change without writing")
    ap.add_argument("--legacy-label", default=None,
                    help="internal Major_group label to rename to "
                         f"{LEGACY_LABEL_REPLACEMENT!r}; omit against a redacted tree")
    ap.add_argument("--legacy-columns", default=None,
                    help="comma-separated old=new column headers to rename in "
                         f"{COMB_ANN_NAME}; omit against a redacted tree")
    ap.add_argument("--source-root", type=Path, default=ROOT,
                    help="repository holding the unredacted source-of-truth tables "
                         "(default: this repository)")
    args = ap.parse_args()
    column_renames = parse_column_renames(args.legacy_columns)

    try:
        loaded = load_cohort_tables(args.source_root.resolve())
    except AlreadyRedacted as exc:
        print(f"Nothing to do: {exc}")
        return 0
    prop_cohorts, open_cohorts, prop_ids, open_ids, prop_counts = loaded
    is_public = make_is_public(prop_cohorts, open_cohorts, prop_ids, open_ids)

    # Longest-first with boundary guards so that a short identifier can never match
    # inside a longer one that merely starts with it.
    id_pattern = re.compile(
        r"(?<![\w.\-])(?:"
        + "|".join(re.escape(i) for i in sorted(prop_ids, key=len, reverse=True))
        + r")(?![\w.\-])"
    )

    print(f"proprietary cohorts : {len(prop_cohorts)}")
    print(f"proprietary sample IDs: {len(prop_ids)}")
    print(f"mode                : {'CHECK (no writes)' if args.check else 'WRITE'}\n")

    for path in sorted(SUPP.rglob("Supplementary File 1.csv")):
        print(f"[SF1 ] {path.relative_to(ROOT)}\n       "
              f"{redact_supp_file_1(path, prop_cohorts, args.legacy_label, args.check)}")
    for path in sorted(SUPP.rglob("Supplementary File 2.csv")):
        print(f"[SF2 ] {path.relative_to(ROOT)}\n       {redact_supp_file_2_csv(path, is_public, args.check)}")
    for path in sorted(SUPP.rglob("Supplementary File 2.xlsx")):
        print(f"[SF2x] {path.relative_to(ROOT)}\n       {redact_supp_file_2_xlsx(path, is_public, args.check)}")

    comb_ann = ROOT / COMB_ANN_NAME
    if comb_ann.exists():
        print(f"[ANN ] {comb_ann.relative_to(ROOT)}\n       "
              f"{redact_comb_ann_public(comb_ann, prop_ids, args.legacy_label, column_renames, args.check)}")

    log_dir = ROOT / "shambhala_adoption" / "Shambhala_containerized" / "logs"
    for name in ("shambhala_pod_logs_260516.txt", "shambhala_pod_logs_260517.txt"):
        path = log_dir / name
        print(f"[LOG ] {path.relative_to(ROOT)}\n       {redact_log(path, id_pattern, args.check)}")

    for directory in sorted({p.parent for p in SUPP.rglob("Supplementary File 1.csv")}):
        print(f"[NOTE] {write_withheld_note(directory, prop_counts, EXPECTED_PUBLIC_ROWS, len(open_cohorts), args.check)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
